# Generated by Django 5.1.1 on 2024-09-11 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('payment_terms', models.TextField()),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_package', models.CharField(max_length=255)),
                ('service_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
